version: '3.1'
services:
  telenot:
    container_name: telenot
    restart: always
    environment:
      MQTTHOST: ${MQTT_HOST}
      MQTTPORT: ${MQTT_PORT}
      MQTTUSER: ${MQTT_USER}
      MQTTPASSWORD: ${MQTT_PASSWORD}
      TELNETHOST: ${TELENOT_HOST}
      TELNETPORT: ${TELENOT_PORT}
      DISCOVER: ${DISCOVER}
    build:
      context: .
      dockerfile: Dockerfile

