version: '3.1'
services:
  telenot:
    container_name: telenot
    restart: always
    environment:
      MQTTHOST: ${MQTTHOST}
      MQTTPORT: ${MQTTPORT}
      MQTTUSER: ${MQTTUSER}
      MQTTPASSWORD: ${MQTTPASSWORD}
      TELNETHOST: ${TELNETHOST}
      TELNETPORT: ${TELNETPORT}
      DISCOVER: ${DISCOVER}
      PUBLISHTOPIC: ${PUBLISHTOPIC}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /srv/docker-config/telenot/config/config.js:/usr/src/app/config/config.js:ro
      - /srv/docker-config/telenot/main:/usr/src/app/main
