version: '3.1'
services:
  telenot:
    container_name: telenot
    restart: always
    environment:
      MQTTHOST: ${MQTTHOST}
      MQTTPORT: ${MQTTPORT}
      MQTTUSER: ${MQTTUSER}
      MQTTPASSWORD: ${MQTTPASSWORD}
      TELNETHOST: ${TELENOTHOST}
      TELNETPORT: ${TELENOTPORT}
      DISCOVER: ${DISCOVER}
      PUBLISHTOPIC: ${PUBLISHTOPIC}
    build:
      context: .
      dockerfile: Dockerfile

